erDiagram
    FINANCING {
        int loan_id PK
        decimal loan_amount
        int loan_term
        string loan_installment_frequency
    }
    STAFF {
        int staff_id PK
        string staff_type
        decimal salary
        string license_number FK
        date issue_date
        date expiration_date
        string renewal_status
    }
    MEDICAL_PROFESSIONAL {
        int medical_professional_id PK
        int staff_id FK
        string license_number PK
        date issue_date FK
        date expiration_date FK
        string renewal_status FK
    }
    PATIENT {
        int patient_id PK
        int medical_record_id FK
        int billing_record_id FK
    }
    BILLING_RECORD {
        int billing_record_id PK
        int patient_id FK
        string insurance_provider_name
        string insurance_subscriber_id
        string coverage_type
        decimal amount_owed
        decimal amount_paid_by_insurance
        decimal amount_paid_by_patient
    }
    INSURANCE_PROVIDER {
        int insurance_provider_id PK
        string name
    }
    SCHEDULING {
        int scheduling_id PK
        int patient_id FK
        int doctor_id FK
        int room_id FK
        datetime date
        datetime time
    }
    ROOM {
        int room_id PK
        string name
    }
    PROCEDURE_CODE {
        int procedure_code_id PK
        string code
    }
    INSURANCE_CLAIM {
        int insurance_claim_id PK
        int billing_record_id FK
        int procedure_code_id FK
        datetime date
        decimal amount
        decimal amount_paid
    }
    FACILITIES {
        int facilities_id PK
        int lease_id FK
    }
    LEASE {
        int lease_id PK
        int facility_id FK
        date lease_start_date
        date lease_end_date
        decimal lease_payment
    }
    REPORTING {
        int reporting_id PK
        string day_schedule
        decimal end_of_day_income
        decimal monthly_expenditure_vs_income
    }
    PATIENT ||--o{ SCHEDULING : schedules
    STAFF ||--o{ MEDICAL_PROFESSIONAL : employs
    MEDICAL_PROFESSIONAL ||--o{ SCHEDULING : serves
    BILLING_RECORD ||--o{ INSURANCE_CLAIM : generates
    INSURANCE_PROVIDER ||--o{ INSURANCE_CLAIM : provides
    SCHEDULING ||--o{ ROOM : occurs
    MEDICAL_RECORD {
        int medical_record_id PK
        int patient_id FK
    }
    SCHEDULING_STATE {
        int scheduling_state_id PK
        string state
    }
    PATIENT ||--o{ MEDICAL_RECORD : has
    SCHEDULING ||--o{ SCHEDULING_STATE : has_state
